project_id = "jooojbaljrshgpaxdlou"

[functions.webhook-greenn]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.create-partner]
verify_jwt = false

[functions.create-partner-artes]
verify_jwt = false
