project_id = "jooojbaljrshgpaxdlou"

[functions.webhook-greenn]
verify_jwt = false

[functions.webhook-greenn-artes]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.create-partner]
verify_jwt = false

[functions.create-partner-artes]
verify_jwt = false

[functions.create-premium-user]
verify_jwt = false

[functions.create-premium-user-artes]
verify_jwt = false

[functions.delete-auth-user-artes]
verify_jwt = false

[functions.update-user-password-artes]
verify_jwt = false
