project_id = "jooojbaljrshgpaxdlou"

[functions.webhook-greenn]
verify_jwt = false

[functions.webhook-greenn-artes]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.create-partner]
verify_jwt = false

[functions.create-partner-artes]
verify_jwt = false

[functions.create-premium-user]
verify_jwt = false

[functions.create-premium-user-artes]
verify_jwt = false

[functions.delete-auth-user-artes]
verify_jwt = false

[functions.update-user-password-artes]
verify_jwt = false

[functions.create-pack-client]
verify_jwt = false

[functions.import-pack-clients]
verify_jwt = false

[functions.process-import-job]
verify_jwt = false

[functions.manage-admin]
verify_jwt = false

[functions.send-email-campaign]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.sendpulse-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.process-scheduled-notifications]
verify_jwt = false

[functions.process-scheduled-emails]
verify_jwt = false

[functions.send-announcement]
verify_jwt = false

[functions.email-unsubscribe]
verify_jwt = false

[functions.process-sending-campaigns]
verify_jwt = false

[functions.welcome-email-tracking]
verify_jwt = false

[functions.upload-to-cloudinary]
verify_jwt = false
