project_id = "jooojbaljrshgpaxdlou"

[functions.webhook-greenn]
verify_jwt = false

[functions.webhook-greenn-artes]
verify_jwt = false

[functions.webhook-greenn-musicos]
verify_jwt = false

[functions.webhook-greenn-creditos]
verify_jwt = false

[functions.create-partner]
verify_jwt = false

[functions.create-partner-artes]
verify_jwt = false

[functions.create-premium-user]
verify_jwt = false

[functions.create-premium-user-artes]
verify_jwt = false

[functions.create-premium-user-musicos]
verify_jwt = false

[functions.delete-auth-user-artes]
verify_jwt = false

[functions.update-user-password-artes]
verify_jwt = false

[functions.create-pack-client]
verify_jwt = false

[functions.import-pack-clients]
verify_jwt = false

[functions.manage-admin]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.process-scheduled-notifications]
verify_jwt = false

[functions.send-announcement]
verify_jwt = false

[functions.email-unsubscribe]
verify_jwt = false

[functions.process-sending-campaigns]
verify_jwt = false

[functions.welcome-email-tracking]
verify_jwt = false

[functions.send-single-email]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false

[functions.delete-auth-user-by-email]
verify_jwt = false

[functions.runninghub-upscaler]
verify_jwt = false

[functions.webhook-hotmart-artes]
verify_jwt = false

[functions.runninghub-webhook]
verify_jwt = false

[functions.runninghub-pose-changer]
verify_jwt = false

[functions.runninghub-veste-ai]
verify_jwt = false

[functions.admin-add-credit-user]
verify_jwt = false
